### ISSUE TITLE
Release 1.3.0 Build Script does not execute correctly (I think!)

### ISSUE THREAD

**Issue by ghost** [IonicaBizau/Flattiance#16]
Hi, I don't know if I am just being a bit thick and I am missing something stupidly obvious, or whether there is a genuine issue here.

I downloaded [v1.3.0 of Flattiance](https://github.com/IonicaBizau/Flattiance/releases/tag/1.3.0) from the releases page, and extracted it to `~/.themes`

On inspecting the contents of the extracted directory, I found a shell script called `./build`. When I first ran this, it complained repeatedly that I did not have `nodejs` or `inkscape` installed.

A solution might be to just place this at the top of the script, rather than letting the entire thing error repeatedly:

```bash
#! /bin/bash

[[ `which inkscape` ]] && [[ `which nodejs` ]] || {
  [[ `which inkscape` ]] || echo "Please install the \"inkscape\" package."
  [[ `which nodejs` ]]   || echo "Please install the \"nodejs\" package."
  exit 1
}
```

The second issue was once these packages were installed, it was not resolving the file names correctly. I was just getting it trying to match the file `.svg`, which doesn't exist. I am guessing this is a mistake as there is no file with this name. I don't know JavaScript well enough to sort this out, otherwise I would try to do it myself and put a pull request in (but I have never done that to another repo before, so I am kind of nervous!)

Is there any reason to be using nodejs? By the looks of it, you are just trying to pass each icon to inkscape, right? Can you not just use sed instead of invoking node? It would reduce the number of required packages, and sed is included with most distros anyway?

Hope this is of some use! If any other info is needed, just let me know.

# Operating System used:
```bash
cat /etc/lsb-release && uname -a
```
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Linux fujitsu 4.8.0-51-generic #54~16.04.1-Ubuntu SMP Wed Apr 26 16:00:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

# Nodejs version used:

```bash
nodejs -v
```
```
v4.2.6
```

# Inkscape version used
```bash
inkscape -V
```
```
Inkscape 0.91 r13725
```

**Comment by IonicaBizau** [comment]
No, you don't need Node.js or Inkscape to use this theme.

Follow the installation section: https://github.com/IonicaBizau/Flattiance#installation

The build script is used by me to generate the image files.

**Comment by ghost** [comment]
Ah! My bad! Thanks ^_^
